name: Install with UV
description: Installs uv and the environment as an action

inputs:
  python-version:
    description: Version of python to use
    required: true
    default: "3.10"
  uv-version:
    description: Version of uv to install
    required: true
    default: "0.6.14"
  install-percep:
    description: Whether to install perception dependencies
    type: boolean
    required: true
    default: false

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Initialize the environment and cache
    - name: Init python and uv
      uses: avstack-lab/workflows/.github/actions/init-uv@main
      with:
        python-version: ${{ inputs.python-version }}
        uv-version: ${{ inputs.uv-version }}

    - name: Set up cache
      uses: actions/cache@v3
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/uv.lock') }}

    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: uv run pip --version >/dev/null 2>&1 || rm -rf .venv

    # Install dependences without or with perception extras
    - name: Install bare dependencies
      shell: bash
      if: ${{ ! github.event.inputs.install-percep }}
      run: |
          uv sync
    - name: Install dependencies with perception extras
      shell: bash
      if: ${{ github.event.inputs.install-percep }}
      run: |
          uv sync --extra percep