name: Test with UV
description: Run unit tests for this repository

inputs:
  test-folder:
    description: Location of the folder to test
    required: false
    default: tests

runs:
  using: composite
  steps:
    # - name: Lint with flake8
    #   run: |
    #       # stop the build if there are Python syntax errors or undefined names
    #       uv run flake8 ./avstack --count --max-line-length=127 --show-source --statistics
    - name: Run tests
      shell: bash
      run: |
          uv run pytest ${{ inputs.test-folder }}
